name: PR Preview

on: workflow_call

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build dist
        uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: dist

      - name: Download build examples
        uses: actions/download-artifact@v4
        with:
          name: build-examples
          path: examples

      - name: Set up PR directory
        run: |
          mkdir -p pr-preview/pr${{ github.event.pull_request.number }}
          cp -r dist pr-preview/pr${{ github.event.pull_request.number }}/
          cp -r examples pr-preview/pr${{ github.event.pull_request.number }}/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pr-preview

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Add Preview Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = ${{ github.event.pull_request.number }};
            const baseUrl = `${{ steps.deployment.outputs.page_url }}/pr${prNumber}/examples`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `
            ### 【GitHub Pages 预览链接】

            - [完整模式](${baseUrl}/index.html)
            - [基础版](${baseUrl}/basic.html)
            - [移动端](${baseUrl}/h5.html)
            - [多实例](${baseUrl}/multiple.html)
            - [无工具栏编辑器](${baseUrl}/notoolbar.html)
            - [纯预览模式](${baseUrl}/preview_only.html)
            - [XSS防护](${baseUrl}/xss.html)（默认禁止）
            - [图片所见即所得](${baseUrl}/img.html)
            - [表格所见即所得](${baseUrl}/table.html)
            - [自动编号标题](${baseUrl}/head_num.html)
            - [流式输入（AI对话场景）](${baseUrl}/ai_chat.html)
            - [VIM 编辑模式](${baseUrl}/vim.html)
              `
            });
