name: 'Build Client Release'

on:
  workflow_call:
    inputs:
      client_version:
        required: true
        type: string
jobs:
  release-client-build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            target: aarch64-apple-darwin
            args: '--target aarch64-apple-darwin'
          - platform: macos-latest
            target: x86_64-apple-darwin
            args: '--target x86_64-apple-darwin'
          - platform: ubuntu-latest
            target: ''
            args: ''
          - platform: windows-latest
            target: ''
            args: ''

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          # This ensures the target is installed if it's not empty.
          target: ${{ matrix.target }}
          toolchain: stable

      - name: Ensure x86_64 Target is Installed
        if: matrix.target == 'x86_64-apple-darwin'
        run: rustup target add x86_64-apple-darwin

      - name: Install Linux Dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Build Tauri
        run: |
          yarn --network-timeout 100000
          yarn build
          yarn build:client ${{ matrix.args }}

      - name: Upload macOS Release Asset (aarch64-apple-darwin)
        if: matrix.platform == 'macos-latest' &&  matrix.target == 'aarch64-apple-darwin'
        uses: AButler/upload-release-assets@v3.0
        with:
          files: |
            packages/client/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.dmg
          release-tag: '@cherry-markdown/client@${{ inputs.client_version }}'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS Release Asset (x86_64-apple-darwin)
        if: matrix.platform == 'macos-latest' &&  matrix.target == 'x86_64-apple-darwin'
        uses: AButler/upload-release-assets@v3.0
        with:
          files: |
            packages/client/src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/*.dmg
          release-tag: '@cherry-markdown/client@${{ inputs.client_version }}'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux Release Asset
        if: matrix.platform == 'ubuntu-latest'
        uses: AButler/upload-release-assets@v3.0
        with:
          files: |
            packages/client/src-tauri/target/release/bundle/deb/*.deb;
            packages/client/src-tauri/target/release/bundle/rpm/*.rpm;
            packages/client/src-tauri/target/release/bundle/appimage/*.AppImage
          release-tag: '@cherry-markdown/client@${{ inputs.client_version }}'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows Release Asset
        if: matrix.platform == 'windows-latest'
        uses: AButler/upload-release-assets@v3.0
        with:
          files: |
            packages/client/src-tauri/target/release/bundle/msi/*.msi;
            packages/client/src-tauri/target/release/bundle/nsis/*.exe
          release-tag: '@cherry-markdown/client@${{ inputs.client_version }}'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
